backend:
  name: github
  repo: beta-europe/beta-europe.github.io   # Path to your Github repository
  branch: master    # Branch to update
  base_url: https://cmsauth.beta-europe.org # Path to ext auth provider


media_folder: "assets/images"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    sort: "date:desc" # Default is title:asc
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Post Excerpt (used in archive)", name: "excerpt", widget: "string", required: false}
      - {label: "Link Post (optional)", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Cover Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "feature", widget: "image", class: "thumb"}
          - {label: "Credit Label", name: "credit", widget: "string", required: false}
          - {label: "Credit Link", name: "creditlink", widget: "string", required: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: false}
      - {label: "Social Share", name: "share", widget: "boolean", default: true}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Show Edit Source", name: "source", widget: "boolean", default: true}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "partner"
    label: "Partner"
    folder: "_partners"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Website (e.g. http://meu.eu)", name: "website", widget: "string", required: false}
      - {label: "Twitter Handle (without at)", name: "twitter", widget: "string", required: false}
      - {label: "Mail", name: "mail", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "President", name: "president", widget: "string", required: false}
      - {label: "Country", name: "country", widget: "string", required: true}
      - {label: "Town", name: "town", widget: "string", required: true}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Members", name: "members", widget: "string", required: false}
      - {label: "Geo Location (e.g.: 52.2333,20.8891)", name: "geo", widget: "string", required: false}
      - {label: "Conferences Series", name: "conferences", widget: "list", required: false}
      # - {label: "conferences", name: "conferences", widget: "relation", collection: "conference", searchFields: ["conference"], valueField: "conference"}
      - {label: "Show Edit Source", name: "source", widget: "boolean", default: true, required: false}
      - {label: "Partner Description", name: "body", widget: "markdown", required: false}
  - name: "conference"
    label: "Conference"
    folder: "_conferences"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Partner Slug", name: "partner-slug", widget: "string", required: false}
      # - {label: "Partner Slug", name: "partner-slug", widget: "relation", collection: "partner", searchFields: ["title"], valueField: "slug"}
      - {label: "Conference Series", name: "conference", widget: "string"}
      - {label: "Year", name: "year", widget: "string", required: true}
      - {label: "Conference Start", name: "begin", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Conference End", name: "end", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Mail", name: "mail", widget: "string"}
      - {label: "Website (e.g. http://mywebsite.eu)", name: "website", widget: "string"}
      - {label: "Twitter Handle (without at)", name: "twitter", widget: "string"}
      - {label: "Country", name: "country", widget: "string"}
      - {label: "Town", name: "town", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Participant Number", name: "participants", widget: "string"}
      - {label: "Geo Location (e.g.: 52.2333,20.8891)", name: "geo", widget: "string"}
      - {label: "Show Edit Source", name: "source", widget: "boolean", default: true, required: false}
      - {label: "Topic Excerpt (used in archive)", name: "excerpt", widget: "string"}
      - {label: "Conference Description", name: "body", widget: "markdown", required: false}
